### PR TITLE
[Core] Modify ObjList and ObjListData to support swapping

### PR DESCRIPTION
**Pull request by lmatz**
Still need to change a lot. And issues about the interfaces exposed to user by ObjList.

### CODE REVIEW

**Comment by lmatz** [comment]
I think supporting swapping only a subset of pages, eg. sort the ObjList when it cannot be entirely put in memory, like how the database does is really difficult for husky since database can know the schema in advance, but husky currently cannot know what type of fields a user-defined object has;  and "VARCHAR" in database has a limitation of the maximum bytes it can take, but husky currently doesn't have that limit. So what we really have is the BinStream which is returned by custom-defined serialization function, but as long as we use the BinStream, then we don't really have a way to know how husky should divide the BinStream into pages so that we can deserialize a page correctly.

**Comment by lmatz** [comment]
The travis fails the TestObjList.Large which is test case for testing swapping. It runs successfully on projgw, maybe the memory size specified by MemoryPool is too large for the travis?

**Comment by kygx-legend** [comment]
Maybe. I checked the memory in travis ci, it's about 7.5G totally. We should handle the situation like this, bad alloc, too.

**Comment by kygx-legend** [comment]
Can you try to reduce the memory that case requires to use first?

**Comment by lmatz** [comment]
I change it to 128\*1024*1024 128MB, and HuskyUnitTest runs successfully on projgw.

**Review by kygx-legend — APPROVED** [review]

**Pull request merged**
